### ISSUE TITLE
Add language menu settings popover

### ISSUE THREAD

**Issue by EnnoKirsimae** [Voog/design-sapporo#101]
Add settings popover to language menu: enables the user to set different display modes for the language menu, ex. expand the menu language horizontally.

**Comment by kaspar-naaber** [comment]
@SSirjes testimistulemused:
* [ ] Laiendatud otsing - puudub nupp 'Lisa saidile uus keel'

![screen shot 2016-08-24 at 19 15 44](https://cloud.githubusercontent.com/assets/13623224/17938629/6bb6a0e8-6a2f-11e6-9973-cad8c4b42206.png)

* [ ] Mobiil, laiendatud otsing - kui keelevalik on lai, siis mobiilis läheb päise all olev pilt üpriski kirjuks. Pakun välja, et teatud reso peal võiks keelevalik ikkagi minna dropdown menüü alla?

![screen_shot_2016-08-25_at_08_39_19](https://cloud.githubusercontent.com/assets/13623224/17958121/dd210a78-6a9f-11e6-965d-53a7678469b8.png)

* [ ] Mobiilse menüü ja 'Settings' vahel võiks olla väike vahe  @ehk paddingut.

![screen_shot_2016-08-25_at_08_49_34](https://cloud.githubusercontent.com/assets/13623224/17958281/27f260fa-6aa1-11e6-81ee-2a5a019fd93c.png)

* [ ] 'Settings' nupp võiks olla keelevaliguga samamoodi joondatud, muidu jookseb väga mobiilse menüü/otsingu sisse.

Võiks olla:
![screen shot 2016-08-25 at 08 59 43](https://cloud.githubusercontent.com/assets/13623224/17958479/fa3408a6-6aa2-11e6-969d-cae48c9980d7.png)

Praegu:
![screen shot 2016-08-25 at 09 01 31](https://cloud.githubusercontent.com/assets/13623224/17958482/feab22fc-6aa2-11e6-9ace-6093fe1f16c8.png)

![screen shot 2016-08-25 at 09 07 53](https://cloud.githubusercontent.com/assets/13623224/17958568/83d4d964-6aa3-11e6-9a82-3f4313d6ddf1.png)

* [ ] Preview ja LIVE vaates võiks otsingu ja keelevaliku vahe olla sama, mis otsingu ja mobiilsel menüül

![screen_shot_2016-08-25_at_09_11_05](https://cloud.githubusercontent.com/assets/13623224/17958688/53a08d28-6aa4-11e6-8240-6be4c27467e3.png)

**Comment by SSirjes** [comment]
* [ ] *Format: 'Expanded' - Search: disabled* 
Between lang.menu and search should be white space

![screen_shot_2016-08-25_at_16_13_08](https://cloud.githubusercontent.com/assets/13623224/17970427/4092308e-6adf-11e6-85fb-969a6c1ac76c.png)

* [ ] *Format: 'dropdown' - Search: disabled*
Between lang.menu and search should be white space

![screen shot 2016-08-25 at 16 30 19](https://cloud.githubusercontent.com/assets/13623224/17971140/32b6085c-6ae2-11e6-9f17-ce598701e24c.png)
