### ISSUE TITLE
Product related layouts tweaks.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-sapporo#134]
- [x] "Hide categories from main menu" -> Show in main menu.
- [x] Check if submenus are working as indended.
- [x] Add breadcrumbs.

**Comment by SSirjes** [comment]
**_Breadcrumbs:_**
* [ ] Not active menu item should maybe have brighter text color like main menu? 

_Maby like this_
![screen_shot_2017-01-06_at_10_44_46](https://cloud.githubusercontent.com/assets/13623224/21712426/72f71986-d3fd-11e6-92ee-91205f5d0513.png)

**Comment by SSirjes** [comment]
"Hide categories from main menu" -> Show in main menu

* [ ] Products layout are displayed in preview, live mode, when 'Show in main menu' is not active

**Comment by SSirjes** [comment]
* [ ] Product layout should not have '+ Add subpage' button

![screen_shot_2017-01-09_at_09_32_43](https://cloud.githubusercontent.com/assets/13623224/21759735/4ae086cc-d64f-11e6-9e73-116be257a9ee.png)

**Comment by kaspar-naaber** [comment]
## Additional tasks for "Product" layout.
- [ ] Add specific placeholder for "drag product here".
- [ ] Convert description area to `{% contentblock %}` with description.

**Comment by SSirjes** [comment]
* [ ] product list need smaller z-index compared with main menu dropdown

![screen_shot_2017-01-09_at_16_45_02](https://cloud.githubusercontent.com/assets/13623224/21770278/37211534-d68b-11e6-8fc5-67d0b7c7c25c.png)

**Comment by SSirjes** [comment]
* [ ] If root layout is 'Product', then 'Settings' - 'Show in main menu' button function don't work

**Comment by SSirjes** [comment]
* [ ] Root 'Settings' button function don't apply immediately, needs refresh

**Comment by SSirjes** [comment]
* [ ] Should 'Product' layout display 'Untranslated' menu item button? 

![screen_shot_2017-01-10_at_12_59_30](https://cloud.githubusercontent.com/assets/13623224/21804299/ecda4f02-d736-11e6-82db-ff54cf4173ab.png)
