### ISSUE TITLE
Add loading / success indicators for content item boxes

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-sapporo#135]
At the moment the preview and save functions are out of sync. User can see the preview even if image is not actually saved.

- [x] Add loader while dropped image is processed.
- [x] Remove loader when dropped image is saved.
- [x] Show image after image is saved, and never before.

**Comment by SSirjes** [comment]
* [ ] Product layout > photo block should not have working loading. 

![screen shot 2017-01-23 at 13 47 36](https://cloud.githubusercontent.com/assets/13623224/22202805/8a60669a-e172-11e6-961e-90854f421e54.png)

Video: http://recordit.co/YvR1boEnHo
