### ISSUE TITLE
Text block: photo stays out of container

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#15]
1. Drag photo into text block, where photo don't fit into text block container
![screen shot 2016-01-25 at 16 27 30](https://cloud.githubusercontent.com/assets/13623224/12553499/96d5dcf4-c380-11e5-890d-6c9c6cf9155b.png)

**Comment by kaspar-naaber** [comment]
Images that are set as wide as content area are designed to go 200px wider from both sides (in this template, becuase it was designed so). That's not a bug.
