### ISSUE TITLE
Form: single choices background color is different from other

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#16]
![screen shot 2016-01-25 at 16 35 53](https://cloud.githubusercontent.com/assets/13623224/12553735/bd801a08-c381-11e5-9f9e-8dfd0d904e17.png)

**Comment by kaspar-naaber** [comment]
Radio buttons and checkboxes msut have different style (radio button aka "single choice" rectangle is empty inside.

But I can see another issue related to inputs. It's very hard to distinct the checkboxes from the bg-color. @runnel – should we change the default bg-color or form fields color?

**Comment by runnel** [comment]
Have a 0,5 px black border on both checkboxes and radio buttons. It will look like 50% black on non-hidpi screens and it will be supe thin line on a retina display. Just like the language box line should be. Look it up in sketch file.

**Comment by kaspar-naaber** [comment]
0.5px border is rendered as 1px border on non-retina displays. Is that okay? Demo: http://sapporo-demo.voog.construction/forms

**Comment by runnel** [comment]
Yes, it's as intended.

**Comment by kaspar-naaber** [comment]
Ok!

**Comment by SSirjes** [comment]
iPod: single choice has white border
![img_0076](https://cloud.githubusercontent.com/assets/13623224/13773257/07bb7a4a-eaa1-11e5-8f6d-de9bc77244f4.jpg)
