### ISSUE TITLE
Form: checkboxes bug

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#17]
http://recordit.co/2Oi4cOO1CH

Screenshot:
![screen shot 2016-01-25 at 16 46 05](https://cloud.githubusercontent.com/assets/13623224/12554055/6c1959d4-c383-11e5-90bc-54ac4ad15a42.png)

**Comment by kaspar-naaber** [comment]
Fixed in 2023080e8fd87a700e2a7da43a97c97de9c2112a
