### ISSUE TITLE
Table style

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#20]
..is table without border?
![screen shot 2016-01-26 at 11 37 03](https://cloud.githubusercontent.com/assets/13623224/12577155/46741f90-c421-11e5-8333-416f432f5d91.png)

**Comment by kaspar-naaber** [comment]
Forms use style borrowe from Barcelona/Madrid. Should I use the table styles from there aswell?

![screenshot 2016-02-11 14 46 41](https://cloud.githubusercontent.com/assets/3191867/12976638/5c6312d4-d0ce-11e5-809c-44b92084ee7d.png)

**Comment by runnel** [comment]
Yes, just make the lines 30% of current opacity.

**Comment by kaspar-naaber** [comment]
Fixed in faad2fa7b36ae3eaf11eee028cc960c1b7e6e6f3
