### ISSUE TITLE
Edit mode: main menu item is displayed under dropdown submenu 

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#21]
Edit mode:
![screen shot 2016-01-26 at 11 44 06](https://cloud.githubusercontent.com/assets/13623224/12577301/2a6e5aee-c422-11e5-9d9e-3b05fc2b7092.png)

Preview, submenu will not displayed:
![screen shot 2016-01-26 at 11 46 21](https://cloud.githubusercontent.com/assets/13623224/12577366/834fa514-c422-11e5-82aa-779aafb570bb.png)

**Comment by kaspar-naaber** [comment]
If item has children then the main page itself should be included in the popup (that's how @runnel wanted). If there's no items yet then it might not be a good idea to display this item before "add button". I will remove it in editmode if there are no children yet.
