### ISSUE TITLE
Language menu with flag, has no active style

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#23]
Language menu with flag, has no active style (like text blod or ring)
![screen shot 2016-01-26 at 12 15 50](https://cloud.githubusercontent.com/assets/13623224/12577956/9643980c-c426-11e5-9e7b-00c66d0c9e25.png)

Text language menu, where active language item has ring after text
![screen shot 2016-01-26 at 12 17 28](https://cloud.githubusercontent.com/assets/13623224/12578017/f6d3e334-c426-11e5-8736-df90fe0244b8.png)

**Comment by kaspar-naaber** [comment]
Menu with no flags has the circle to mark the active language.

![screenshot 2016-02-11 14 34 31](https://cloud.githubusercontent.com/assets/3191867/12976420/9f47081e-d0cc-11e5-80b5-997a02b009bd.png)

In flags mode there's nothing that highlights the active menu

**Comment by runnel** [comment]
Lets just ditch the flags from this design. It should be minimalist.

**Comment by kaspar-naaber** [comment]
The main reason why we added the language flags toggleing option was to prevent manual work for the customers who would like to turn their menu into flags or text based.

If we ditch that from this template and this kind of request comes from the support then what should we do? Manual work or decline this request? If we are not going to decline these kinds of requests then wouldn't it be wiser to have that feature in the template from the beginning?

(Custom modifications also means that the templates will be set as "custom" and are not automatically updated with standard design updates)

**Comment by runnel** [comment]
If you can set non-flag as the default option, then okay by me.

**Comment by runnel** [comment]
<img width="436" alt="language-flags" src="https://cloud.githubusercontent.com/assets/462527/13104420/ade38ac6-d565-11e5-9744-8a01e6152e1f.png">

**Comment by kaspar-naaber** [comment]
Non-flag is already the default. I will add the active marker like you designed.

**Comment by kaspar-naaber** [comment]
Marker added.
