### ISSUE TITLE
Footer default text style is not well visible

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#24]
![screen shot 2016-01-26 at 14 59 55](https://cloud.githubusercontent.com/assets/13623224/12581168/8b37e33e-c43d-11e5-8983-e12ed19069c6.png)

**Comment by kaspar-naaber** [comment]
Question for designer.

**Comment by runnel** [comment]
Lets leave it as it is. We might have a need to tweak Windows fonts anyway. So let's solve (if necessary) font issues globally.
