### ISSUE TITLE
Mobile menu 

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#25]
* [x] if menu item is long, then submenu "arrow" are too close 
* [x]  mobile menu width is too short, why not to make width bit wider
* [ ] submenu is open only then, when I click to arrow icon (it's very small). Would it be clearer if all list element opens submenu

![screen shot 2016-01-26 at 15 27 53](https://cloud.githubusercontent.com/assets/13623224/12581761/6990f71c-c441-11e5-8ce0-3724ef18bd7d.png)

**Comment by kaspar-naaber** [comment]
I agree with the first checkbox but others needs input from @runnel 
* Menu is as wide as it was designed. Should we change that?
* Icon clickable area is 27x32 (px). We can't set title itself to open submenu because the title is a page a separate page.

**Comment by runnel** [comment]
Menu should be either some percentage of screen size or have more than one breaking point. Let's try the first option initially — let's set it to be 40%. Show me! :)

**Comment by runnel** [comment]
Clicking on a menu point which has at least one submenu item will open submenu which shows both the child and upper element inside the submenu. Having a clickable area only on arrow is a bad practice.

**Comment by kaspar-naaber** [comment]
The submenu solution is still a bit confusing. At the moment it works like this:
* If main page has sub-items, then it has the arrow button behind the name
* If user clicks on the arrow (or its padding around it) it will show the sub menu content.
* If user clicks on the main menu element name (not the icon or its padding) he/she will be directed to the main menu page and after opening the menu from there again, it shows the submenu with a possibility to go back into main menu.

Demo: http://recordit.co/5jZs44OLj6

Is that the way it should work or should clicikng on the main menu element's name also toggle the sub menu (like it does on clicking the arrow) and from there the user can select to the main menu page (PHOTOS in that case) if he/she decides so?

**Comment by kaspar-naaber** [comment]
BTW http://sapporo-demo.voog.com now has 40% wide mobile menu.

**Comment by runnel** [comment]
Tapping on a main menu link which has submenu should not navigate to another page but only open the submenu.
