### ISSUE TITLE
Common page: menu item block in content

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#26]
1. If i create menu item, then in content appears menu item text. Is it right?
2. ...if I add to this block photo, then I can't edit it
![screen shot 2016-01-26 at 16 06 05](https://cloud.githubusercontent.com/assets/13623224/12582583/bf038782-c446-11e5-942d-4ee2845e2605.png)

**Comment by kaspar-naaber** [comment]
1. It is correct behaviour. The default title of the page is the name of the page which can be edited or removed. Just like in https://github.com/Voog/design-barcelona or https://github.com/Voog/design-berlin.

2. The image in "max-width" mode should be 100% of the viewport and this is an issue.
