### ISSUE TITLE
Link style don't distinct from common tekst

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#27]
![screen shot 2016-01-26 at 16 16 23](https://cloud.githubusercontent.com/assets/13623224/12582855/4f6d54aa-c448-11e5-9284-d74bf2fa9718.png)

Common vs link text
![screen shot 2016-01-26 at 16 18 13](https://cloud.githubusercontent.com/assets/13623224/12582882/6ce0d034-c448-11e5-8c6c-529b0bf486c3.png)

**Comment by kaspar-naaber** [comment]
It sure is kind of hard to distinct them. Body text is black with 0.8 alpha and the link is solid black, but with the font-weight 300 (light) they look almost the same.

**Comment by runnel** [comment]
Links should always be bold (regular), whereas normal text is usually ultra light.
