### ISSUE TITLE
"Hidden", "+Add" button and language menu, search are too close (need some padding top)

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#31]
Edit mode:
![screen shot 2016-01-27 at 12 22 52](https://cloud.githubusercontent.com/assets/13623224/12610482/b81319f6-c4f0-11e5-9dcc-da06a94b2a3d.png)

**Comment by kaspar-naaber** [comment]
This is something that only appears on the edge cases:
* User have a so many pages in the main menu that the take entire container width (in desktop mode)
* User must be in editmode

Adding this padding also affect the layout in desktop mode and it is impossible to detect the situation without JS. #44 will fix this issue.
