### ISSUE TITLE
Blog article image adding options

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#33]
1. Postituse pildi saab valida "Lehe seadete" alt. Kas võiks olla analoog võimalus, kus pildi saaks lisada otse sisuala sisse nii nagu Paris kujunduses.
![screen shot 2016-01-27 at 16 06 56](https://cloud.githubusercontent.com/assets/13623224/12615718/0781cb26-c510-11e5-8c07-cf5ed0d4ffd9.png)

**Comment by kaspar-naaber** [comment]
As I understand, we have taken the direction where page settings image shouldn't be the image that is displayed on the page itself. It should be an image for the social media.

Due to that we we might need an image drop area somewhere in editmode – @runnel

**Comment by runnel** [comment]
Let's do it just like in the Barcelona template — image is inserted in the same place where it is shown.

It would be worthwhile to also research the additional feature — fetching the blog post cover image from the post content with javascript. If user replaces or deletes it from the front page the new choice will prevail.
