### ISSUE TITLE
Blog post tags appear in main menu dropdown submenu

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#34]
![screen shot 2016-01-27 at 16 15 56](https://cloud.githubusercontent.com/assets/13623224/12616372/831c6072-c513-11e5-8ac7-5b7543a1a100.png)

**Comment by kaspar-naaber** [comment]
This is the correct location for the blog tags in this template. By default we do not allow adding sub pages to the blog type pages. Every other page type will list it's sub pages in this popup but blog lists the tags in the same place.
