### ISSUE TITLE
Blog tags filtering block is missing

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#35]
Like this:
![screen shot 2016-01-27 at 16 54 11](https://cloud.githubusercontent.com/assets/13623224/12638297/a5b68b80-c5a4-11e5-960d-6fe3bcb53da8.png)

**Comment by kaspar-naaber** [comment]
Blog tags are listed under the blog page in menu:

![screenshot 2016-02-11 11 07 23](https://cloud.githubusercontent.com/assets/3191867/12972660/c8c2e48c-d0af-11e5-8134-2300cb455c18.png)

**Comment by SSirjes** [comment]
If there is lot of tags, should it become under scroll?
![screen shot 2016-03-11 at 16 16 50](https://cloud.githubusercontent.com/assets/13623224/13704501/f8ae8d20-e7a4-11e5-8357-19fb4c4473e7.png)

**Comment by kaspar-naaber** [comment]
I guess inner scroll is not neccessary. It will increase the body height and entire body can scroll down if neccessary. The only thing is passes the footer at some point but it looks like an edge case anyway.

If I set the body background the same as the main container, than it should be okay or what you think @runnel ?

* At the moment:
![screenshot 2016-03-14 08 53 46](https://cloud.githubusercontent.com/assets/3191867/13737011/6bc1f184-e9c2-11e5-94a4-d6d3c3e6ed36.png)

* After the update:
![screenshot 2016-03-14 08 55 29](https://cloud.githubusercontent.com/assets/3191867/13737020/8b3d963a-e9c2-11e5-9239-8a3fb5d1350e.png)

**Comment by kaspar-naaber** [comment]
If the solution I provided is okay, then it is already done: 32b82c1585ed02e133e63ca557ddbf9292326df8
Issue can be closed if theres nothing to add.

**Comment by kaspar-naaber** [comment]
I discussed it with @runnel and the solution was okay.
