### ISSUE TITLE
Article without article photo

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#37]
Kui postitusel puudub pilt - kuidas lahendada pealkirja paiknemine?
Kas äkki postituse pealkiri joondada keskele, default taustapilt või postitusele õrn joon ümber? 

1. Edit mode. Kui lisatud kaks postitust. Esimesed kaks postitust ei paista silma.
![screen shot 2016-01-27 at 14 38 30](https://cloud.githubusercontent.com/assets/13623224/12615611/5908c090-c50f-11e5-92eb-509a77a0455a.png)

2. Front-page. Kuidas paigutada, kliendi poolt, ilma pildita postituse pealkiri? Default taustapilt postitusele?
![screen shot 2016-01-28 at 10 25 10](https://cloud.githubusercontent.com/assets/13623224/12638931/793fb50e-c5a9-11e5-8586-8dfb24ae7d27.png)

**Comment by runnel** [comment]
On front page, lets have it like this:

![home](https://cloud.githubusercontent.com/assets/462527/12973958/02df8630-d0b9-11e5-97a9-5e8e1a0e4b20.jpg)

**Comment by kaspar-naaber** [comment]
Fixed in 86929f1bead43d273fbea7927d0af4a34fb8541c
