### ISSUE TITLE
Blog article max-width

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#40]
Should it have max-width?
![screen shot 2016-01-28 at 16 24 08](https://cloud.githubusercontent.com/assets/13623224/12647020/e1a0dc22-c5db-11e5-8c4a-7e1e0588153a.png)

**Comment by kaspar-naaber** [comment]
Could you please explain what do you mean by that? :)

**Comment by kaspar-naaber** [comment]
As we discussed in IRL it should be as designed.
