### ISSUE TITLE
Article image aspect ratio in mobile view

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-sapporo#46]
Should the images (and text placeholders) collapse to the height that they are natively in mobile view:
http://recordit.co/0lpY5vstQo

or should they maintain the square aspect ratio?
http://recordit.co/sqwHXj4ns5

**Comment by runnel** [comment]
Let's keep the aspect ratio. But on a sidenote — why not use the dual column layout as proposed in sketch?

<img width="407" alt="sapporo-mobile" src="https://cloud.githubusercontent.com/assets/462527/13103247/5f7ea332-d55d-11e5-8096-06244d4e9e3f.png">

**Comment by kaspar-naaber** [comment]
There is a dual column layout between 720px and 481px but it collapses to one column if screen is <=480. In my opinion the images became too small on smaller mobile screens but I can remove one-column entirely or reduce the breakpoint.

**Comment by runnel** [comment]
You are making this assessment based on oldschool pre-retina mobile screens or non-retina desktop. Please try it on a 320px retina eg ipod touch instead. Also — don't loose the breakpoint — there are different paddings and some text sizes differ on 320px and 375+ px screens.

Also, 480px is larger than any normal phone. Even iPhone 6+ is 'only' 414px :)

**Comment by kaspar-naaber** [comment]
The items keep the aspect ratio and breaks to one column only on very small screens.
08084653d553f0293bc6e87d7096346a79c22453
