### ISSUE TITLE
Blog: if blog post don't have photo, then blog dropdown menu blends with white background

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#49]
![screen shot 2016-03-10 at 10 58 07](https://cloud.githubusercontent.com/assets/13623224/13664380/8eeedef8-e6af-11e5-8c41-c900a2867fe4.png)

**Comment by kaspar-naaber** [comment]
Some possible solutions:

1. Border around the popover:
![screenshot 2016-03-11 09 40 30](https://cloud.githubusercontent.com/assets/3191867/13696213/7962222a-e76d-11e5-8c7d-5e61dd422ec9.png)

2. Box shadow arount the popover:
![screenshot 2016-03-11 09 43 14](https://cloud.githubusercontent.com/assets/3191867/13696240/b90671a6-e76d-11e5-8d81-db9da1764312.png)

3. @runnel ?

**Comment by runnel** [comment]
Let's do nothig. Sooner or later other browsers start supporting background blur and whiteness in itself isn'ta problem.
