### ISSUE TITLE
Safari: language menu "use flags" option covers extra dot before search

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#53]
Closed language menu:
![screen shot 2016-03-11 at 14 01 14](https://cloud.githubusercontent.com/assets/13623224/13703226/1a0cf4d2-e79d-11e5-983c-e1ac02997343.png)

Language menu is open:
![screen shot 2016-03-11 at 14 01 26](https://cloud.githubusercontent.com/assets/13623224/13703227/1bacd6c2-e79d-11e5-8bed-faf87d2d7c00.png)

**Comment by kaspar-naaber** [comment]
The dot should be active language item indicator and visible only when language popup is open. I'll investigate why it shows before the earch icon while menu is closed.

**Comment by SSirjes** [comment]
The dot is back in Safari: http://recordit.co/saJPrTiIQM

Preview:
![Uploading Screen Shot 2016-03-28 at 17.45.29.png…]()

**Comment by kaspar-naaber** [comment]
I restored some old code and accidentally restored this bug aswell. Fixed: 68070e119317534c41c40a8c5fea485c21525e5a
