### ISSUE TITLE
Add design editor support.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-sapporo#57]
- [x] Setup grunt task to build `.tpl` component from sources stylesheet.
- [x] Add custom styles component to `template-head.tpl`.
- [x] Render options based on layout.
- [x] Regroup editors.
- [x] Add footer editor.
- [x] Add title editor.
- [x] Add article editor

**Kaspar:** Because article uses the same styles as content area text then I guess it is okay if the "content" editor changes the article also. If not then we might fix it in the future.

- [x] Add comment form editor

**Kaspar:** Because comment uses the same styles as content area form then I guess it is okay if the "form" editor changes the comment form also. If not then we might fix it in the future.

- [x] Add comments editor

**Kaspar:** I decided to keep it simple and leave it out from the first iteration. If still needed then we can add it in the future.

- [x] Add content form editor
- [x] Add content gallery editor

**Kaspar:** Galleries have many different layouts. I guess the modifications should be added undes each gallery settings instead of design editor. There's not many things we can style anyway.

- [x] Add content list editor.
- [x] Add article tags editor

**Kaspar:** I decided to keep it simple and leave it out from the first iteration. If still needed then we can add it in the future.

- [x] Separate styles into partials.

**Comment by SSirjes** [comment]
* [ ] Colors - Secondary color don't change all color like article heading

**Comment by SSirjes** [comment]
* [ ] Only front page layout has in design toolbar "Blog"
![screen_shot_2016-04-13_at_16_19_29](https://cloud.githubusercontent.com/assets/13623224/14521254/1f819a9a-0231-11e6-9d9b-48394b782a3c.png)

**Comment by kaspar-naaber** [comment]
- [ ] Add form button style editing

**Comment by SSirjes** [comment]
* [ ]  IE(11) + add new blog post text is out of container

Put "BLOG" - Max. number of columns to maximum. Result: text will go out of container
![untitled-1](https://cloud.githubusercontent.com/assets/13623224/14604364/e44abe9a-057b-11e6-8f7c-3bb11cf66d52.jpg)

**Comment by kaspar-naaber** [comment]
- [ ] Make a slimmer version.

**Comment by SSirjes** [comment]
* [ ] Adding more than 6 columns to blog, it will display only max 5 columns
Video: http://recordit.co/IAw4UiMJ3j

**Comment by SSirjes** [comment]
* [ ] Form background color is applied (some opacity) also to filed bg colo. If you put to form field background color white, then there stays light green 
![screen shot 2016-04-19 at 11 18 54](https://cloud.githubusercontent.com/assets/13623224/14632489/a8c713fe-0621-11e6-9458-35456efaca6d.png)

**Comment by kaspar-naaber** [comment]
- [x] Set header menu mode only when changing variables that can change the width of the relevant elements that can cause menu mode changing.

**Comment by SSirjes** [comment]
* [ ]  **List takes in default design editor values**

Screenshot: 

![screen shot 2016-04-20 at 11 21 39](https://cloud.githubusercontent.com/assets/13623224/14667885/1eac2aa0-06ea-11e6-9cbd-5be6ee8668c4.png)

Video: http://recordit.co/MgZMNnKPQc

**Comment by SSirjes** [comment]
* [ ]  **Form background color don't apply in (IE)**

If I change some other color or text, then modified form background color changes are coming to visible until refresh

**Comment by SSirjes** [comment]
* [ ] Content padding will not apply in Internet Explorer(11)

**Comment by SSirjes** [comment]
* [ ] **Table font size don't change**
![screen shot 2016-04-20 at 14 46 57](https://cloud.githubusercontent.com/assets/13623224/14673492/e3be525c-0706-11e6-866e-0791dcf09b63.png)

**Comment by kaspar-naaber** [comment]
Reopen if something new is discovered.

**Comment by SSirjes** [comment]
* [ ] **Should comment text also get main styles font in writing process?**
![screen_shot_2016-04-26_at_12_27_22](https://cloud.githubusercontent.com/assets/13623224/14813517/b638c6b6-0baa-11e6-83da-c83923961237.png)
