### ISSUE TITLE
Mobile: page title line height is too high

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#58]
![sre](https://cloud.githubusercontent.com/assets/13623224/13794837/b335bc22-eb06-11e5-9473-7340a65b456c.jpg)

In mobile line-height is too high
![slice 1](https://cloud.githubusercontent.com/assets/13623224/13794818/8858a302-eb06-11e5-8f1b-e6aff6ee528f.png)

**Comment by kaspar-naaber** [comment]
Fixed: 79aa464ec919e28e08a066aa4a050b8f14bef469
