### ISSUE TITLE
Article view don't cover mobile menu

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#76]
![screen shot 2016-03-24 at 12 52 50](https://cloud.githubusercontent.com/assets/13623224/14015116/66e049ea-f1bf-11e5-9dcc-d878e9e8fd0b.png)

**Comment by kaspar-naaber** [comment]
Seems to be the test site issue only. Didn't find out exact reason why it happens but I tested on many sites and it didn't occur.

Reopen if this bug is discovered on other sites.
