### ISSUE TITLE
Touchpad: main menu don't covers properly (dropdown)submenu

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#80]
Tested in iPad
1. click on menu, what has submenus (if menu is not under mobile menu)
2. it navigates right to clicked mainmenu page. Submenu will be coverd just a moment
Video, what happens: http://recordit.co/JjXiYFwy5M

**Comment by kaspar-naaber** [comment]
It now prevents menu main touch and opens popover menu on touchscreens where user can select the main menu item from popover.

**Comment by SSirjes** [comment]
Submenu is now working. 
But now if I want move between main menu I can't do it. If I click on main menu, it will open submenu and if I want go to main menu page, it will not open - opens only submenu.

**Comment by kaspar-naaber** [comment]
The main menu item itself can be opened from the sub menu (first item in the list). Now it is a question for a designer which behavior is correct:

Solution 1
* If user clicks on the main menu item on touch screen, it will open the sub menu and doesn't visit the main menu page immediately.
* If user clicks on main menu item and the sub menu is already open it should close the sub menu.
* Only way to visit the main menu page with sub menu on touch screen is to click on the first item in the sub menu:
![screenshot 2016-03-28 08 58 42](https://cloud.githubusercontent.com/assets/3191867/14071952/4da632b2-f4c3-11e5-92fd-609efdbd98b3.png)

Solution 2
* If user clicks on the main menu item on touch screen, it will open the sub menu and doesn't visit the main menu page immediately.
* If user clicks on main menu item and the sub menu is already open it visits the main menu item page.

**Comment by runnel** [comment]
1 :)

**Comment by kaspar-naaber** [comment]
It already works as intended then! :)
