### ISSUE TITLE
Should commenter name be bolder as comment text?

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#81]
Design:
![screen shot 2016-03-24 at 16 30 46](https://cloud.githubusercontent.com/assets/13623224/14020002/f2ecc3aa-f1dd-11e5-8e9e-193754503832.png)

Now:
![screen shot 2016-03-24 at 16 32 30](https://cloud.githubusercontent.com/assets/13623224/14020020/08800330-f1de-11e5-88d8-4e958fe9d1a0.png)

**Comment by SSirjes** [comment]
WIndows computer bolder text don't distingt, is ok?
![kommentaar](https://cloud.githubusercontent.com/assets/13623224/14082851/fe0faa46-f51a-11e5-879a-56a071901f1a.jpg)

**Comment by kaspar-naaber** [comment]
Tegin paremaks!
