### ISSUE TITLE
Front page: older post alignment

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#83]
Would it be better, if older post without photos where aligned left - better legibility? Also bit smaller font size for post title?
Like this:
![ch2](https://cloud.githubusercontent.com/assets/13623224/14064582/d6d8db1a-f410-11e5-909a-6a7093428385.jpg)

Now:
![cg1](https://cloud.githubusercontent.com/assets/13623224/14064603/5f162906-f411-11e5-82ed-3fd73b16b6a3.jpg)

**Comment by runnel** [comment]
Nope :) The question is, as always, about the good housekeeping of the site owner. The result is terrible no matter the layout — if the owner fails to think about the visual outcome of different headline lengths.

![news](https://cloud.githubusercontent.com/assets/462527/14065388/e356be60-f42f-11e5-89c5-60b691c55df2.jpg)

**Comment by kaspar-naaber** [comment]
I will close it then! :)
