### ISSUE TITLE
With layout "Blog news" can't add new blog post

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#85]
Is it right, that there is two same layout - "Blog news" and "Blog and news"?
![untitled-1](https://cloud.githubusercontent.com/assets/13623224/14064788/cf31c5f4-f418-11e5-87b4-7096c6c55f17.jpg)

**Comment by kaspar-naaber** [comment]
Some error with the manifest file accidentally generated this "Blog news" layout. I removed it now.
