### ISSUE TITLE
Android, Window phone header differences

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-sapporo#88]
Android, Windows phone - if I put logo into header, this is the result:
![screenshot_20160328-184839](https://cloud.githubusercontent.com/assets/13623224/14081938/e51c54da-f515-11e5-89f3-5532a68b9736.png)

Is it correct?

**Comment by kaspar-naaber** [comment]
I ended up aligning header content center. It became really difficult to handle header different states (with or without search button, compact menu, flags, etc and all the possible combinations with them).

Probably 90% of the cases user fills the field with one (or two max.) line string or small image. If the image or text height is not very long it should be okay. (or what? @runnel)
http://recordit.co/X1iapgVwzW

**Comment by runnel** [comment]
Ok.
