### ISSUE TITLE
Add blog comments section.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-sapporo#9]
- [x] Design (@runnel)
- [ ] Code (@kaspar-naaber)

**Comment by runnel** [comment]
![sapporo-first-comment](https://cloud.githubusercontent.com/assets/462527/12978070/6b7c5362-d0d7-11e5-94d2-538b0d9252cc.jpg)

![sapporo-first-comment-insert](https://cloud.githubusercontent.com/assets/462527/12978072/6f4a4bc0-d0d7-11e5-930f-31f2d2383568.jpg)

![sapporo-comments](https://cloud.githubusercontent.com/assets/462527/12978075/731a74a0-d0d7-11e5-8807-1c81dff51ba3.jpg)

**Comment by kaspar-naaber** [comment]
1. Clicking on the "write comment" will toggle the visibility of other form components?
2. Should I update he content area forms to use same styles as this form?

**Comment by runnel** [comment]
1. Yes. I think it's like this in Berlin theme.
2. Good idea.
